language: node_js
node_js:
  - "7"

sudo: false

git:
    submodules: false

before_script:
    - npm install

before_install:
  - mysql -e 'CREATE DATABASE IF NOT EXISTS rv2projTest;'
  - mysql -e 'CREATE USER IF NOT EXISTS $MYSQL_USER@"localhost" IDENTIFIED BY $MYSQL_PASS;'
  - mysql -e 'GRANT ALL ON rv2projTest.* to $MYSQL_USER@"localhost";'
  - mysql -u$MYSQL_USER rv2projTest < db/sql/ddl.sql
  - mysql -u$MYSQL_USER rv2projTest < db/sql/insert.sql

script:
    - npm test

after_success:
#     - npm run report-codecov
    - npm run report-codacy
