language: node_js
node_js:
  - "7"

sudo: false

git:
    submodules: false

before_script:
    - npm install

before_install:
  - mysql -e 'CREATE DATABASE IF NOT EXISTS rv2projTest;'
  - mysql -e 'CREATE USER IF NOT EXISTS "test"@"localhost" IDENTIFIED BY "test";'
  - mysql -e 'GRANT ALL ON rv2projTest.* to "test"@"localhost";'
  - mysql -utest -ptest rv2projTest < db/sql/ddl.sql
  - mysql -utest -ptest rv2projTest < db/sql/insert.sql

script:
    - npm test

after_success:
#     - npm run report-codecov
    - npm run report-codacy
