language: node_js
node_js:
  - "7"

sudo: false

git:
    submodules: false

before_script:
    - npm install

script:
    - npm test

after_success:
#     - npm run report-codecov
    - npm run report-codacy
